### ISSUE TITLE
폭이 좁을수록 알림과 메시지 창이 비정상적으로 표시되는 문제

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki.com#81]
![image](https://user-images.githubusercontent.com/28209361/30445917-8ac9b222-99c2-11e7-8740-b5a1786602ae.png)

위와 같이 화면 폭이 일정 수치 이하일 때는, 그 폭이 작으면 작을수록 알림과 메시지 창이 정상적으로 표시되지 않는 문제가 있습니다.

**Comment by pinkrespect** [comment]
아직 팔로업이 끝나지 않아 무언가를 섣불리 말씀 드리기는 어렵지만 해상도 보다는 화면 종횡비의 문제로 보입니다.
어떤 환경에서 재현되는지 이슈를 읽다가 궁금해서 확인해 보았는데,
갤럭시
노트 5 WQHD(2560 x 1440) 환경에서도 똑같은 현상이 발견됩니다.

**Comment by lens0021** [comment]
https://femiwiki.com/w/주제:Tykuvys4bqj0795j

**Comment by lens0021** [comment]
This issue was moved to femiwiki/skin#8
